config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
  root "tasks#index"
  resources :users, only: [:edit, :update]
  resources :groups, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  has_many :goal_users
  has_many :users, through: :goal_users
  balidates :content, presence: true, uniqueness: true
end

app/models/goal_user.rb
class GoalUser < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def new
  end

  def create
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html{lang: "ja"}
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    / Required meta tags
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1, shrink-to-fit=no", name: "viewport"}/
    / Bootstrap CSS
    %link{crossorigin: "anonymous", href: "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css", integrity: "sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh", rel: "stylesheet"}/
    %title Tweet
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = yield

    / Optional JavaScript
    / jQuery first, then Popper.js, then Bootstrap JS
    %script{crossorigin: "anonymous", integrity: "sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n", src: "https://code.jquery.com/jquery-3.4.1.slim.min.js"}
    %script{crossorigin: "anonymous", integrity: "sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo", src: "https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"}
    %script{crossorigin: "anonymous", integrity: "sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6", src: "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"}

app/views/tasks/index.html.haml
.header
  %h1 Tasks#index
  .header__limit
.tasks
  .tasks__content
    %p Find me in app/views/tasks/index.html.haml
  .tasks__limit
.fooder
  = link_to edit_user_path(current_user) do
    = icon('fas', 'cog', class: 'icon')
    edit

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      = link_to "Log out", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "Back to the top page", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'